Document: xerxes
Title: Debian xerxes Manual
Author: <insert document author here>
Abstract: This manual describes what xerxes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xerxes/xerxes.sgml.gz

Format: postscript
Files: /usr/share/doc/xerxes/xerxes.ps.gz

Format: text
Files: /usr/share/doc/xerxes/xerxes.text.gz

Format: HTML
Index: /usr/share/doc/xerxes/html/index.html
Files: /usr/share/doc/xerxes/html/*.html

  
